-- MOZ BUSINESS — SUPABASE / POSTGRESQL
-- Este ficheiro é apenas para referência/recriação. O SQL já foi executado no projeto do utilizador.

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'business' CHECK (role IN ('business','admin')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    city TEXT NOT NULL,
    description TEXT NOT NULL,
    phone TEXT,
    whatsapp TEXT,
    instagram TEXT,
    facebook TEXT,
    tiktok TEXT,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
    active_plan TEXT,
    plan_status TEXT NOT NULL DEFAULT 'inactive' CHECK (plan_status IN ('inactive','active','expired')),
    plan_expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    video_filename TEXT,
    duration_seconds INTEGER,
    destination_url TEXT,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    amount_mzn INTEGER NOT NULL,
    description TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    plan_code TEXT NOT NULL,
    amount_mzn INTEGER NOT NULL,
    method TEXT NOT NULL CHECK (method IN ('MPESA','EMOLA')),
    payer_phone TEXT NOT NULL,
    reference TEXT NOT NULL UNIQUE,
    provider_payment_id TEXT,
    status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','PAID','FAILED','CANCELLED')),
    failure_reason TEXT,
    paid_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS webhook_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_event_id TEXT NOT NULL UNIQUE,
    payload TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS payment_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    method TEXT NOT NULL UNIQUE CHECK (method IN ('MPESA','EMOLA')),
    phone TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

INSERT INTO plans (code,name,amount_mzn,description) VALUES
('basico','Básico',500,'A empresa aparece nas pesquisas do Moz Business.'),
('premium','Premium',700,'Pesquisa + perfil completo com fotos, serviços, contactos e redes sociais.'),
('anuncio','Anúncio',1500,'Publicidade para TikTok e Facebook. Vídeo até 30 segundos e sujeito a aprovação.')
ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name,amount_mzn=EXCLUDED.amount_mzn,description=EXCLUDED.description;

INSERT INTO payment_contacts (method,phone) VALUES
('MPESA','858804425'),('EMOLA','865742391')
ON CONFLICT (method) DO UPDATE SET phone=EXCLUDED.phone;

CREATE INDEX IF NOT EXISTS idx_companies_owner ON companies(owner_id);
CREATE INDEX IF NOT EXISTS idx_companies_status ON companies(status);
CREATE INDEX IF NOT EXISTS idx_companies_category ON companies(category);
CREATE INDEX IF NOT EXISTS idx_companies_city ON companies(city);
CREATE INDEX IF NOT EXISTS idx_ads_company ON ads(company_id);
CREATE INDEX IF NOT EXISTS idx_ads_status ON ads(status);
CREATE INDEX IF NOT EXISTS idx_payments_user ON payments(user_id);
CREATE INDEX IF NOT EXISTS idx_payments_company ON payments(company_id);
CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status);
